@host = http://localhost:5257

GET {{host}}/api/projects
Accept: application/json

###

GET {{host}}/openapi/v1.json
Accept: application/json

###

POST {{host}}/api/projects
Content-Type: application/json

{
  "name": "Trackr API",
  "description": "Backend du projet Trackr"
}

###

POST {{host}}/api/projects
Content-Type: application/json

{
  "name": "Trackr frontend",
  "description": "Interface React du projet Trackr"
}

###

POST {{host}}/api/projects
Content-Type: application/json

{
  "name": "",
  "description": "Projet invalide"
}

###

GET {{host}}/api/projects/1
Accept: application/json

###

GET {{host}}/api/projects/99999
Accept: application/json

###

PUT {{host}}/api/projects/1
Content-Type: application/json

{
  "name": "Trackr Backend",
  "description": "API ASP.NET Core pour le gestionnaire d'issues Trackr"
}

###

PUT {{host}}/api/projects/99999
Content-Type: application/json

{
  "name": "Test",
  "description": "Test"
}

###
