@host = http://localhost:5257

GET {{host}}/api/projects
Accept: application/json

###

GET {{host}}/openapi/v1.json
Accept: application/json

###

POST {{host}}/api/projects
Content-Type: application/json

{
  "name": "Trackr API",
  "description": "Backend du projet Trackr"
}

###