@host = http://localhost:5257

GET {{host}}/api/projects
Accept: application/json

###

GET {{host}}/openapi/v1.json
Accept: application/json

###

GET {{host}}/api/projects/2
Accept: application/json

###

GET {{host}}/api/projects/99999
Accept: application/json

###

POST {{host}}/api/projects
Content-Type: application/json

{
  "name": "Trackr API",
  "description": "Backend du projet Trackr"
}

###

POST {{host}}/api/projects
Content-Type: application/json

{
  "name": "Trackr frontend",
  "description": "Interface React du projet Trackr"
}

###

POST {{host}}/api/projects
Content-Type: application/json

{
  "name": "",
  "description": "Projet invalide"
}

###

PUT {{host}}/api/projects/3
Content-Type: application/json

{
  "name": "Trackr Backend",
  "description": "API ASP.NET Core pour le gestionnaire d'issues Trackr"
}

###

PUT {{host}}/api/projects/99999
Content-Type: application/json

{
  "name": "Test",
  "description": "Test"
}

###

DELETE {{host}}/api/projects/1

###

GET {{host}}/api/projects/2/issues
Accept: application/json

###

GET {{host}}/api/projects/2/issues/1
Accept: application/json

###

GET {{host}}/api/projects/99999/issues/1
Accept: application/json

###

POST {{host}}/api/projects/2/issues
Content-Type: application/json

{
  "title": "Add authentication",
  "description": "Implement user login and registration."
}

###

POST {{host}}/api/projects/3/issues
Content-Type: application/json

{
  "title": "Add issue details",
  "description": "Create endpoint for retrieving an individual issue."
}

###

POST {{host}}/api/projects/99999/issues
Content-Type: application/json

{
  "title": "Invalid issue",
  "description": "This project does not exist."
}

###

POST {{host}}/api/projects/2/issues
Content-Type: application/json

{
  "title": "",
  "description": "Invalid issue"
}

###

PUT {{host}}/api/projects/2/issues/1
Content-Type: application/json

{
  "title": "Update authentication flow",
  "description": "Improve the login and registration workflow.",
  "status": "InProgress"
}

###

PUT {{host}}/api/projects/99999/issues/1
Content-Type: application/json

{
  "title": "Invalid update",
  "description": "This issue does not belong to this project."
}

###

PUT {{host}}/api/projects/1/issues/1
Content-Type: application/json

{
  "title": "Add authentication",
  "description": "Implement login and registration.",
  "status": "AlmostDone"
}

###

DELETE {{host}}/api/projects/2/issues/3

###


